FROM quay.io/quarkus/centos-quarkus-maven:21.0-java11 AS builder
ARG BUILD_DIR=/usr/src/app
USER root
RUN mkdir -p ${BUILD_DIR} && chown quarkus ${BUILD_DIR}
WORKDIR ${BUILD_DIR}
COPY --chown=quarkus ./ ./
USER quarkus
RUN mvn -Pnative clean package -Dmaven.wagon.http.ssl.insecure=true -Dmaven.wagon.http.ssl.allowall=true -Dmaven.wagon.http.ssl.ignore.validity.dates=true

FROM aashipov/htmltopdf:base
# no trailing slash
ARG BUILD_DIR=/usr/src/app
USER root
COPY --from=builder --chown=dummy:dummy ${BUILD_DIR}/target/app /dummy/app
EXPOSE 8080
USER dummy
WORKDIR /dummy
CMD ./app -Dquarkus.http.host=0.0.0.0