FROM aashipov/docker:builder AS builder
ARG BUILD_DIR=/dummy/build
USER root
WORKDIR ${BUILD_DIR}
COPY --chown=dummy:dummy ./ ./
USER dummy
WORKDIR ${BUILD_DIR}
RUN gradle build shadowJar --no-daemon -Dfile.encoding=UTF-8

FROM aashipov/docker:base
ARG BUILD_DIR=/dummy/build
USER root
COPY --chown=dummy:dummy --from=builder ${BUILD_DIR}/build/libs/htmltopdf*shadow.jar /dummy/app.jar
WORKDIR /dummy/
EXPOSE 8080
USER dummy
CMD java -jar app.jar
