---
apiVersion: v1
kind: Namespace
metadata:
  name: htmltopdf-javase

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: htmltopdf-javase
  labels:
    app: htmltopdf-javase
  namespace: htmltopdf-javase
spec:
  replicas: 1
  selector:
    matchLabels:
      app: htmltopdf-javase
  template:
    metadata:
      labels:
        app: htmltopdf-javase
    spec:
      containers:
      - name: htmltopdf-javase
        image: aashipov/htmltopdf-javase:pure
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          protocol: TCP
        volumeMounts:
        - mountPath: /dummy/tmp
          name: tmp-volume
      volumes:
        - name: tmp-volume
          emptyDir:
            medium: Memory
---
apiVersion: v1
kind: Service
metadata:
  name: htmltopdf-javase
  namespace: htmltopdf-javase
spec:
  type: ClusterIP
  #type: NodePort
  selector:
    app: htmltopdf-javase
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      #nodePort: 30080

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: htmltopdf-javase
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
  namespace: htmltopdf-javase
spec:
  rules:
  - http:
      paths:
      - path: /pdf
        pathType: Prefix
        backend:
          service:
            name: htmltopdf-javase
            port:
              number: 8080
